### PR TITLE
Updated support for PCF 2.3

### PR DESCRIPTION
**Pull request by amiramm**

### CODE REVIEW

**Comment by jknostman3** [comment]
@amiramm Thanks!

**Comment by jncd** [comment]
Hi @amiramm, A quick question about the release note update "Update SB to work with PCF v2.2" 
What exactly is meant by SB — I don't see that acronym anywhere else in the doc.

**Comment by amiramm** [comment]
SB = Service Broker.

**Comment by jncd** [comment]
Thanks. I changed the SBs to "Redis Enterprise Service Broker".

**Comment by jncd** [comment]
Also made some other fixes to that neglected release notes page.

**Pull request merged**
